---
name: build
on:
  push:
    tags:
      - v*
    branches:
      - main
      - master
  pull_request:
permissions:
  contents: write
  pull-requests: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build main PCB
        uses: INTI-CMNB/KiBot@v2
        with:
          config: main/config.kibot.yaml
          dir: main
          schema: main/main.sch
          board: main/main.kicad_pcb
      - name: Build sub PCB
        uses: INTI-CMNB/KiBot@v2
        with:
          config: sub/config.kibot.yaml
          dir: sub
          schema: sub/sub.sch
          board: sub/sub.kicad_pcb
      - name: Build STL file
        uses: flat35hd99/openscad-actions@v1.4
        with:
          scad_file: bracket/bracket.scad
          output_file: bracket/bracket.stl
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr@1.8.5
      - name: Install libraries
        run: |
          arduino-cli lib update-index
          arduino-cli lib install digitalWriteFast@1.1.0
          arduino-cli lib install FreqCount@1.3.0
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Files
          path: |
            main/output/main-bom.csv
            main/output/main-jlcpcb.zip
            sub/output/sub-bom.csv
            sub/output/sub-jlcpcb.zip
            bracket/bracket.stl
          if-no-files-found: warn
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            main/output/main-bom.csv
            main/output/main-jlcpcb.zip
            sub/output/sub-bom.csv
            sub/output/sub-jlcpcb.zip
            bracket/bracket.stl
